/*
 
Created with NetBeans

 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;


       
import javax.swing.JOptionPane;
import javax.swing.UIManager;





public class frame102 extends javax.swing.JFrame {

    public String matchTest = " ";
    
    

    /**
     * Creates new form frame1
     */
    public frame102() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        newSearchButton = new javax.swing.JButton();
        ReportButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PerMatch = new javax.swing.JTextArea();
        ProgressBar = new javax.swing.JProgressBar();
        PiePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MatchedWords = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        overusedWords = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        mismatchedWords = new javax.swing.JTextArea();
        WordsThatMatch = new javax.swing.JLabel();
        MissedWordsResume = new javax.swing.JLabel();
        OverusedWords = new javax.swing.JLabel();
        BasedOnButton = new javax.swing.JButton();
        backgroundPick = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        paste = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resume Analyzer");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setForeground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(240, 80));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        newSearchButton.setBackground(new java.awt.Color(51, 51, 51));
        newSearchButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        newSearchButton.setIcon(new javax.swing.ImageIcon("/Users/natallia/Desktop/search1-black.png")); // NOI18N
        newSearchButton.setText("New search");
        newSearchButton.setToolTipText("");
        newSearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        newSearchButton.setFocusPainted(false);
        newSearchButton.setIconTextGap(10);
        newSearchButton.setPreferredSize(new java.awt.Dimension(300, 60));
        newSearchButton.setSelectedIcon(new javax.swing.ImageIcon("/Users/natallia/Desktop/search1-green.png")); // NOI18N
        newSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(newSearchButton);

        ReportButton.setBackground(new java.awt.Color(51, 51, 51));
        ReportButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ReportButton.setIcon(new javax.swing.ImageIcon("/Users/natallia/Desktop/report1-black.png")); // NOI18N
        ReportButton.setText("View report");
        ReportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        ReportButton.setFocusTraversalPolicyProvider(true);
        ReportButton.setIconTextGap(20);
        ReportButton.setPreferredSize(new java.awt.Dimension(300, 60));
        ReportButton.setSelected(true);
        ReportButton.setSelectedIcon(new javax.swing.ImageIcon("/Users/natallia/Desktop/report1-green.png")); // NOI18N
        jPanel1.add(ReportButton);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1020, 60));

        PerMatch.setEditable(false);
        PerMatch.setColumns(15);
        PerMatch.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PerMatch.setLineWrap(true);
        PerMatch.setRows(2);
        PerMatch.setToolTipText("");
        PerMatch.setWrapStyleWord(true);
        PerMatch.setMargin(new java.awt.Insets(10, 50, 10, 30));
        PerMatch.setSelectionColor(new java.awt.Color(0, 153, 153));
        PerMatch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PerMatchCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(PerMatch);

        jPanel3.add(jScrollPane2);

        ProgressBar.setBackground(new java.awt.Color(153, 153, 255));
        ProgressBar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ProgressBar.setBorderPainted(false);
        ProgressBar.setPreferredSize(new java.awt.Dimension(280, 50));
        ProgressBar.setStringPainted(true);
        jPanel3.add(ProgressBar);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 140));

        PiePanel.setMaximumSize(new java.awt.Dimension(150, 150));
        PiePanel.setPreferredSize(new java.awt.Dimension(100, 100));
        PiePanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PiePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 280, 300));

        MatchedWords.setEditable(false);
        MatchedWords.setColumns(51);
        MatchedWords.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        MatchedWords.setLineWrap(true);
        MatchedWords.setRows(9);
        MatchedWords.setTabSize(3);
        MatchedWords.setAlignmentX(1.0F);
        MatchedWords.setAlignmentY(1.0F);
        MatchedWords.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                MatchedWordsCaretUpdate(evt);
            }
        });
        MatchedWords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MatchedWordsMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(MatchedWords);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 680, 140));

        overusedWords.setEditable(false);
        overusedWords.setColumns(51);
        overusedWords.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        overusedWords.setLineWrap(true);
        overusedWords.setRows(9);
        overusedWords.setWrapStyleWord(true);
        overusedWords.setAlignmentX(1.0F);
        overusedWords.setAlignmentY(1.0F);
        overusedWords.setSize(new java.awt.Dimension(500, 150));
        jScrollPane4.setViewportView(overusedWords);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 680, 160));

        mismatchedWords.setEditable(false);
        mismatchedWords.setColumns(51);
        mismatchedWords.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        mismatchedWords.setLineWrap(true);
        mismatchedWords.setRows(9);
        mismatchedWords.setTabSize(4);
        mismatchedWords.setWrapStyleWord(true);
        mismatchedWords.setAlignmentX(1.0F);
        mismatchedWords.setAlignmentY(1.0F);
        mismatchedWords.setSize(new java.awt.Dimension(500, 150));
        jScrollPane3.setViewportView(mismatchedWords);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 680, 130));

        WordsThatMatch.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        WordsThatMatch.setText("Matching words");
        WordsThatMatch.setToolTipText("");
        getContentPane().add(WordsThatMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 280, 20));

        MissedWordsResume.setFont(new java.awt.Font("STIXIntegralsUp", 1, 18)); // NOI18N
        MissedWordsResume.setText("Words you should add to your resume");
        getContentPane().add(MissedWordsResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 20));

        OverusedWords.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        OverusedWords.setText("Overused words");
        getContentPane().add(OverusedWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 190, 20));

        BasedOnButton.setText("based on words");
        BasedOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasedOnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BasedOnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 280, 20));

        backgroundPick.setIcon(new javax.swing.ImageIcon("/Users/natallia/Desktop/resulazer/img/tarquoise2.jpg")); // NOI18N
        backgroundPick.setText("jLabel1");
        backgroundPick.setMinimumSize(new java.awt.Dimension(1200, 1155));
        backgroundPick.setPreferredSize(new java.awt.Dimension(1200, 1155));
        getContentPane().add(backgroundPick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 620));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        paste.setText("Edit");
        paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText(" Copy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        paste.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(" Cut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        paste.add(jMenuItem1);

        JMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItem3.setText(" Paste");
        JMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem3ActionPerformed(evt);
            }
        });
        paste.add(JMenuItem3);

        jMenuBar1.add(paste);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("reportPage");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       
    
    
    private void newSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSearchButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        frame1 page1 = new frame1();
        page1.setVisible(true);
        
        
    }//GEN-LAST:event_newSearchButtonActionPerformed

    private void MatchedWordsCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_MatchedWordsCaretUpdate
        // TODO add your handling code here:
        
        
       // MatchedWords.setText(frame1.resumeInput);
        
        
        
    }//GEN-LAST:event_MatchedWordsCaretUpdate

    private void MatchedWordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchedWordsMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_MatchedWordsMouseExited

    private void PerMatchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PerMatchCaretUpdate
        // TODO add your handling code here:
        
       // PerMatch.setText(nounParseTest.GO().percentMatch);
        
    }//GEN-LAST:event_PerMatchCaretUpdate

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // copy text:
       // TextFieldResume.copy();
        //TextFieldJob.copy();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // cut text:

        //TextFieldResume.cut();
        //TextFieldJob.cut();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem3ActionPerformed
        // paste text:

        //TextFieldResume.paste();
       // TextFieldJob.paste();

    }//GEN-LAST:event_JMenuItem3ActionPerformed

    private void pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteActionPerformed

    }//GEN-LAST:event_pasteActionPerformed

    private void BasedOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasedOnButtonActionPerformed
        
        FieldBased BasedOnPage = new FieldBased();
        nounParseTest.pushTheButton();
        BasedOnPage.setVisible(true);
        
        
    }//GEN-LAST:event_BasedOnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
       UIManager.put("ProgressBar.selectionBackground", Color.black);
       UIManager.put("ProgressBar.selectionForeground", Color.white);
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasedOnButton;
    private javax.swing.JMenuItem JMenuItem3;
    public static javax.swing.JTextArea MatchedWords;
    private javax.swing.JLabel MissedWordsResume;
    private javax.swing.JLabel OverusedWords;
    public static javax.swing.JTextArea PerMatch;
    public static javax.swing.JPanel PiePanel;
    public static javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton ReportButton;
    private javax.swing.JLabel WordsThatMatch;
    private javax.swing.JLabel backgroundPick;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea mismatchedWords;
    private javax.swing.JButton newSearchButton;
    public static javax.swing.JTextArea overusedWords;
    private javax.swing.JMenu paste;
    // End of variables declaration//GEN-END:variables
}
