

//library for KEYWORDS search in resume and job description

public class keyWordsAPI {

  public static void main(String[] arg){

  System.out.println(library1);

  }

static String library1 = "people history art world information map family government health system computer music method data law bird literature problem software knowledge power economics internet television science library nature product idea temperature investment area society industry media community definition safety quality development management \n" +
 " video security exam movie organization equipment physics analysis policy series go direction strategy technology army camera paper environment child instance truth marketing university article department difference goal news audience growth income user combination failure meaning medicine philosophy teacher communication chemistry disease disk energy nation road role location\n" +
  " success education math politics attention decision event property student wood competition distribution entertainment office population president context introduction performance driver flight magazine newspaper relationship cell dealer message phone scene appearance association concept customer death discussion housing inflation insurance mood advice\n" +
  " blood effort expression opinion payment responsibility situation skill statement wealth application city county estate foundation heart perspective photo recipe studio topic collection depression imagination passion percentage resource ad agency college connection criticism debt description memory secretary solution administration aspect attitude director personality psychology recommendation response selection storage\n" +
  " version argument complaint contract emphasis membership preparation union agreement cancer currency employment engineering entry interaction mixture preference region republic tradition virus actor classroom delivery device difficulty drama election engine football guidance hotel owner priority protection suggestion tension variation anxiety atmosphere awareness climate comparison confusion construction elevator\n" +
  " guest leadership mall manager operation recording sample transportation charity disaster editor feedback guitar homework leader outcome permission presentation promotion reflection refrigerator resolution revenue session singer tennis basket bonus cabinet church clothes coffee dinner hearing initiative judgment lab measurement mode mud poetry police procedure\n" +
  " ratio relation restaurant satisfaction sector signature town vehicle accident airport appointment arrival assumption committee conversation database error explanation farmer gate hall historian hospital injury instruction maintenance manufacturer perception pie poem presence proposal reception replacement revolution speech warning winner worker writer assistance \n" +
  " buyer chocolate conclusion contribution cookie establishment examination garbage grocery honey impression improvement independence insect inspection inspector ladder menu penalty piano potato profession professor quantity reaction requirement supermarket tongue weakness wedding affair ambition analyst assignment assistant championship client consequence departure diamond \n" +
  " ear fortune friendship funeral gene negotiation obligation platform pollution recognition reputation surgery sympathy trainer film water money example business study game life air place number field fish process heat hand experience book end point type home economy value body market guide interest state radio\n" +
  " company price card list mind trade care risk word force light training school order practice research sense service piece web boss sport house page term test answer sound focus matter kind soil board oil picture access garden range rate reason site demand exercise image case cause coast action age boat record result section mouse cash class period plan store tax side subject space rule stock\n" +
  " weather chance figure model source earth program design feature head material purpose question rock salt act birth car dog object scale sun note profit rent speed style war bank craft half inside outside standard bus exchange eye fire position pressure stress advantage benefit box frame issue step cycle face item metal paint review room screen structure view account ball discipline medium share balance bit black bottom choice gift impact machine shape\n" +
  " tool wind culture sign table task condition credit network square attempt effect link post voice capital challenge shot brush debate exit front function lack plant spot taste theme track wing brain button desire foot gas influence notice wall base damage distance feeling pair savings staff sugar target text animal author budget discount file\n" +
  " ground lesson officer phase reference register stage title trouble bowl bridge campaign character edge evidence fan letter lock maximum novel option pack park plenty skin weight baby background carry dish factor fruit glass joint master muscle strength traffic trip vegetable appeal chart gear ideal kitchen land log net principle relative sale season signal spirit street tree belt bench commission drop minimum\n" +
  " path progress project sea status stuff ticket tour angle blue breakfast confidence daughter degree doctor dream duty essay fee finance limit peace pipe seat stable storm substance team trick afternoon bat beach blank chain consideration cream crew detail gold interview kid mark match mission pain pleasure score screw shop shower suit tone window agent band block bone calendar cap coat contest corner court cup district door\n" +
  " garage guarantee implement layer lecture lie manner meeting parking partner profile respect routine schedule telephone tip winter airline bag battle bed bill bother cake code curve designer dimension dress emergency extension farm fight gap grade holiday horror horse host husband loan mistake mountain nail noise occasion package patient pause phrase proof race relief sand sentence shoulder smoke stomach string tourist towel\n" +
  " wheel wine arm associate blow border branch breast chip coach cross document draft dust expert floor god habit iron judge landscape league mail mess native parent pattern pin pool pound request salary shame shelter shoe silver tackle tank trust assist bake bar bell bike blame boy brick chair closet clue collar comment conference diet fuel glove jacket lunch monitor mortgage nurse pace peak plane\n" +
  " reward row sandwich shock transition yard alarm bend bicycle bite blind bottle cable candle clerk cloud concert counter flower harm knee lawyer load neck pension plate purple skirt slice snow specialist stroke switch trash tune zone anger award bid bitter boot bug camp candy carpet cat champion channel clock comfort cow crack engineer entrance fault grass hell highlight incident island joke jury\n" +
  " motor nerve passage pride priest prize promise resident resort ring roof rope sail scheme script sock station tower truck witness human \n" +
  " pay let increase single individual turn ask guard hold offer potential international travel cook alternative dance excuse commercial low purchase deal worth produce support return safety \n" +
  " visual affect cover report rise walk junior pick unique anything classic final lift private stop teach concern gain rich fail lead flow objective \n" +
  " opposite remote vast abuse beat burn deposit attack claim soft survey tie adult brief ubuntu redhat\n" +
  " illegal mobile respond senior struggle train convert crash dependent permit quote \n" +
  " team business base skill talent responsibilities design api layer database intelligence tools tableau logi scientists outputs product analytics ui interfaces backends backend software development templates reusable teams requirements usability performance mentor expert linux\n " +
  "javascript perl linux unix quality java python mockito optimizing testing scrum regression bugs resolution results phase framework exploratory j2ee angularjs jquery smalltalk struts jsp velocity hibernate phonegap cordova json linq flex sharepoint sybase access db2 azure \n " +
  " junit framework teamplayer team lider code efficient role degree business unit test toolbar tools mssql xml j2ee tcp ip tcp/ip rest soap aws server c++ c# tomcat framework hibernate maven jdeveloper soa weblogic iis google object lifecycle oos solution requirements methodologies applications license release coursework embedded scripting qt rtos debugging \n " +
  " powershell vbscript packaging profiles lab baseline baselines hardware models wm archetype archetypes batch altris wmi microsoft sccm msi wise gpo cifs dfs mindset memory dump dumps enterprise infrastructure confoguration browser virtualizatiom network workstation netuitive sevone perfmon systrack splunk gradle bitbucket kotlin android espresso robolectric appium \n " +
  " apple chef puppet ansible ip/mpls wireless mse Ethereum Improvement Proposals EIP security threat vulnerability scanning solidity evm blockchain cloud roadmap redhat centos shell selinux apparmor bigdata hadoop storage rbac docker mesos sans cis nis ldap kerberos vmware vsphere xen kvm openstack ec2 cissp gcia terraform devops devsecops csa allience matrix control consensus assessment assessments \n " +
  " firewall waf wafs malware social media platform facebook youtube instagram twitter pinterest planning report channels insights tactic tactics followership engagement voice amazon pr campaign campaigns brand photoshoots selivery samples gift influence trust ownership vendors brands autocad revit proposals contracts plans heating ventilation air elevators vulnerabilities disclosure drawings scheme construction sketches sketchup photshop illustrator indesign materials architects";





}
